name: rag_console
description: rag_console package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  archive: ^4.0.1
  chat:
    path: ../chat
  console:
    path: ../console
  database:
    path: ../database    
  dio: ^5.6.0
  document:
    path: ../document
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  logger:
  responsive_builder: ^0.7.0
  settings:
    path: ../settings
  stacked: ^3.4.3
  stacked_services: ^1.5.0
  surrealdb_js: ^1.0.0-beta.20+5
  surrealdb_wasm: ^1.1.0+16

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito:
  stacked_generator: ^2.0.0
  ulid: ^2.0.0
  very_good_analysis: ^6.0.0

dependency_overrides:
  js: ^0.7.1
  meta: ^1.12.0

flutter:
  uses-material-design: true
