name: settings
description: Settings package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  analytics: 
    path: ../analytics
  database: 
    path: ../database
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2  
  freezed_annotation: ^3.1.0
  fzregex: ^2.0.0
  json_annotation: ^4.9.0
  json_schema: ^5.2.0
  logger:
  stacked: ^3.4.3
  stacked_services: ^1.5.0
  surrealdb_js: ^1.1.0+9
  surrealdb_wasm: ^1.1.0+16
  ui:
    path: ../ui
  ulid: ^2.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.1
  stacked_generator: ^2.0.0
  very_good_analysis: ^6.0.0

dependency_overrides:
  meta: ^1.15.0
  #surrealdb_wasm:
#    path: ../../surrealdb_wasm

flutter:
  uses-material-design: true
  assets:
    - assets/json/llm_providers.json