name: stacked_package_template
description: stacked_package_template package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  logger:
  responsive_builder: ^0.7.1
  stacked: ^3.4.3
  stacked_services: ^1.6.0
  surrealdb_js: ^1.1.0+9
  surrealdb_wasm: ^1.1.0+16

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito:
  stacked_generator: ^2.0.0
  ulid: ^2.0.0
  very_good_analysis: ^9.0.0

dependency_overrides:
  meta: ^1.17.0
  #surrealdb_wasm:
#    path: ../../surrealdb_wasm
    
flutter:
  uses-material-design: true
