name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v4

      - name: Setup Flutter  
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter doctor -v

      - name: Install Melos
        run: dart pub global activate melos

      - name: Melos Bootstrap
        run: melos bootstrap

      - name: Generate Codes
        run: |
          melos generate_packages --no-select
          melos generate

      - name: Setup chrome driver
        uses: nanasess/setup-chromedriver@v2

      - name: Run chrome driver
        run: |
          chromedriver --port=4444 &
          
      - name: Run Integration Tests
        run: melos ci_integration_test --no-select

      - name: Create .env.prod file
        run: echo "${{ secrets.DOT_ENV_FILE }}" > .env.prod

      - name: Update GITHUB_RUN_NUMBER to version
        run: melos update_version
        
      - name: Build
        run: melos build_prod

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: "./build/web"
